var siglePersonArr = [
    { "bodyname": "bashenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 440, "y": 80 },
        "dimname": "mohu",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "bashanguang",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyhairname": "",
        "bodyhairxy": { "x": 0, "y": 0 },
        "bodyisruchanganimation": false,
        "personeishair": false,
        "personruchang": { "data_json": "", "data_png": "", "data_name": "", "x": 62, "y": 75 },
        "personehair": { "data_json": "", "data_png": "", "data_name": "", "x": 0, "y": 0 },
        "personhappy": { "data_json": "fatherhappy_json", "data_png": "fatherhappy_png", "data_name": "fatherhappy", "x": 68, "y": 82 },
        "personsad": { "data_json": "fathersad_json", "data_png": "fathersad_png", "data_name": "fathersad", "x": 68, "y": 82 },
        "personarmname": "bashou",
        "personearmdir": "left",
        "personarmxy": { "x": 0, "y": 145 },
        "shearhandname": "jiandao",
        "shearhandxy": { "x": 0, "y": 145 },
        "xiangkuangxy": { "x": 318, "y": 46 },
        //已拍好的照片名
        "completephotoname": "bazhaopian",
        "completephotoxy": { "x": 311, "y": 39 },
        //正确的结果
        "rightresult": "daddy"
    },
    { "bodyname": "geshenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 424, "y": 219 },
        "dimname": "gemh",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "gesg",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyhairname": "",
        "bodyhairxy": { "x": 0, "y": 0 },
        "bodyisruchanganimation": false,
        "personeishair": false,
        "personruchang": { "data_json": "", "data_png": "", "data_name": "", "x": 62, "y": 75 },
        "personehair": { "data_json": "", "data_png": "", "data_name": "", "x": 0, "y": 0 },
        "personhappy": { "data_json": "gehappy_json", "data_png": "gehappy_png", "data_name": "gehappy", "x": 41, "y": 75 },
        "personsad": { "data_json": "gesad_json", "data_png": "gesad_png", "data_name": "gesad", "x": 41, "y": 75 },
        "personarmname": "geshou",
        "personearmdir": "right",
        "personarmxy": { "x": 8, "y": 136 },
        "shearhandname": "geshou",
        "shearhandxy": { "x": 8, "y": 136 },
        "xiangkuangxy": { "x": 318, "y": 170 },
        //已拍好的照片名
        "completephotoname": "gepz",
        "completephotoxy": { "x": 307, "y": 161 },
        //正确的结果
        "rightresult": "brother"
    },
    { "bodyname": "jieshenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 394, "y": 222 },
        "dimname": "jiemohu",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "jiesg",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyhairname": "jiebian",
        "bodyhairxy": [{ "x": 0, "y": 10 }, { "x": 131, "y": 0 }],
        "bodyisruchanganimation": true,
        "personeishair": true,
        "personehair": { "data_json": "jiebianzi_json", "data_png": "jiebianzi_png", "data_name": "jiebianzi", "x": 0, "y": 0 },
        "personruchang": { "data_json": "jieruchang_json", "data_png": "jieruchang_png", "data_name": "jieruchang", "x": 62, "y": 75 },
        "personhappy": { "data_json": "jiehappy_json", "data_png": "jiehappy_png", "data_name": "jiehappy", "x": 62, "y": 75 },
        "personsad": { "data_json": "jiesad_json", "data_png": "jiesad_png", "data_name": "jiesad", "x": 62, "y": 75 },
        "personarmname": "",
        "personearmdir": "left",
        "personarmxy": { "x": 0, "y": 0 },
        "shearhandname": "",
        "shearhandxy": { "x": 0, "y": 0 },
        "xiangkuangxy": { "x": 317, "y": 160 },
        //已拍好的照片名
        "completephotoname": "jiepz",
        "completephotoxy": { "x": 305, "y": 154 },
        //正确的结果
        "rightresult": "sister"
    },
    { "bodyname": "mashenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 404, "y": 109 },
        "dimname": "mamohu",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "masg",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyhairname": "",
        "bodyhairxy": { "x": 0, "y": 0 },
        "bodyisruchanganimation": true,
        "personeishair": false,
        "personehair": { "data_json": "", "data_png": "", "data_name": "", "x": 0, "y": 0 },
        "personruchang": { "data_json": "maruchang_json", "data_png": "maruchang_png", "data_name": "maruchang", "x": 49, "y": 84 },
        "personhappy": { "data_json": "mahappy_json", "data_png": "mahappy_png", "data_name": "mahappy", "x": 49, "y": 84 },
        "personsad": { "data_json": "masad_json", "data_png": "masad_png", "data_name": "masad", "x": 49, "y": 84 },
        "personarmname": "mashou",
        "personearmdir": "right",
        "personarmxy": { "x": 121, "y": 133 },
        "shearhandname": "mashou",
        "shearhandxy": { "x": 121, "y": 133 },
        "xiangkuangxy": { "x": 318, "y": 64 },
        //已拍好的照片名
        "completephotoname": "mapz",
        "completephotoxy": { "x": 310, "y": 77 },
        //正确的结果
        "rightresult": "mommy"
    },
    { "bodyname": "naishenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 425, "y": 114 },
        "dimname": "naimohu",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "naisg",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyisruchanganimation": true,
        "personeishair": false,
        "personehair": { "data_json": "", "data_png": "", "data_name": "", "x": 0, "y": 0 },
        "personruchang": { "data_json": "nairuchang_json", "data_png": "nairuchang_png", "data_name": "nairuchang", "x": 37, "y": 86 },
        "bodyhairname": "",
        "bodyhairxy": { "x": 0, "y": 0 },
        "personhappy": { "data_json": "naihappy_json", "data_png": "naihappy_png", "data_name": "naihappy", "x": 37, "y": 86 },
        "personsad": { "data_json": "naisad_json", "data_png": "naisad_png", "data_name": "naisad", "x": 37, "y": 86 },
        "personarmname": "",
        "personearmdir": "",
        "personarmxy": { "x": 0, "y": 0 },
        "shearhandname": "",
        "shearhandxy": { "x": 0, "y": 0 },
        "xiangkuangxy": { "x": 318, "y": 77 },
        //已拍好的照片名
        "completephotoname": "naizp",
        "completephotoxy": { "x": 308, "y": 69 },
        //正确的结果
        "rightresult": "grandma"
    },
    { "bodyname": "yeshenti",
        "bodyxy": { "x": 0, "y": 0 },
        "personxy": { "x": 418, "y": 128 },
        "dimname": "yemohu",
        "dimxy": { "x": 0, "y": 0 },
        "flickername": "yesg",
        "flickerxy": { "x": 0, "y": 0 },
        "bodyhairname": "",
        "bodyhairxy": { "x": 0, "y": 0 },
        "bodyisruchanganimation": true,
        "personeishair": false,
        "personehair": { "data_json": "", "data_png": "", "data_name": "", "x": 0, "y": 0 },
        "personruchang": { "data_json": "yeruchang_json", "data_png": "yeruchang_png", "data_name": "yeruchang", "x": 24, "y": 54 },
        "personhappy": { "data_json": "yehappy_json", "data_png": "yehappy_png", "data_name": "yehappy", "x": 24, "y": 54 },
        "personsad": { "data_json": "yesad_json", "data_png": "yesad_png", "data_name": "yesad", "x": 24, "y": 54 },
        "personarmname": "",
        "personearmdir": "",
        "personarmxy": { "x": 0, "y": 0 },
        "shearhandname": "",
        "shearhandxy": { "x": 0, "y": 0 },
        "xiangkuangxy": { "x": 312, "y": 78 },
        //已拍好的照片名
        "completephotoname": "yezp",
        "completephotoxy": { "x": 298, "y": 70 },
        //正确的结果
        "rightresult": "grandpa"
    }
];
